#!/bin/bash

#*******************************************************************************
#  Omicron Player Classic Installer
#
#  Copyright (c) 2015-2019, Fábio Pichler
#  All rights reserved.
#
#  License: BSD 3-Clause License (http://fabiopichler.net/bsd-3-license/)
#  Author: Fábio Pichler
#  Website: http://fabiopichler.net
#
#*******************************************************************************

echo
echo "Omicron Player Classic (Desinstalação)"
echo "Copyright (c) 2015-2019, Fábio Pichler, Todos os direitos Reservados"
echo

if [ ! `whoami` = "root" ]
then
    echo "Para iniciar a desinstalação, é preciso fazer login como root"
    echo
    exit
fi

count=0

echo "Iniciando o programa de desinstalação..."
echo
echo "Removendo arquivos..."

if rm "/opt/omicron-player-classic/" -R
then
    let count++
else
    echo "Erro ao remover os arquivos em: /opt/omicron-player-classic/"
fi

if rm "/usr/share/applications/omicron-player-classic.desktop"
then
    let count++
else
    echo "Erro ao remover o arquivo: /usr/share/applications/omicron-player-classic.desktop"
fi

echo

if [ $count -eq 2 ]
then
    echo "O Omicron Player Classic foi desinstalado com sucesso"
else
    echo "Erro ao desinstalar o Omicron Player Classic"
fi

echo
