#!/bin/bash

#*******************************************************************************
#  Omicron Media Player Installer
#
#  Copyright (c) 2015-2019, Fábio Pichler
#  All rights reserved.
#
#  License: BSD 3-Clause License (http://fabiopichler.net/bsd-3-license/)
#  Author: Fábio Pichler
#  Website: http://fabiopichler.net
#
#*******************************************************************************

echo
echo "Omicron Media Player (Desinstalação)"
echo "Copyright (c) 2015-2019, Fábio Pichler, Todos os direitos Reservados"
echo

if [ ! `whoami` = "root" ]
then
    echo "Para iniciar a desinstalação, é preciso fazer login como root"
    echo
    exit
fi

count=0

echo "Iniciando o programa de desinstalação..."
echo
echo "Removendo arquivos..."

if rm "/opt/Omicron-Player-3/" -R
then
    let count++
else
    echo "Erro ao remover os arquivos em: /opt/Omicron-Player-3/"
fi

if rm "/usr/share/applications/Omicron-Player-3.desktop"
then
    let count++
else
    echo "Erro ao remover o arquivo: /usr/share/applications/Omicron-Player-3.desktop"
fi

echo

if [ $count -eq 2 ]
then
    echo "O Omicron Media Player foi desinstalado com sucesso"
else
    echo "Erro ao desinstalar o Omicron Media Player"
fi

echo
