#!/bin/bash

#*******************************************************************************
#  FPM Player Installer
#
#  Copyright (c) 2015-2019, Fábio Pichler
#  All rights reserved.
#
#  License: BSD 3-Clause License (http://fabiopichler.net/bsd-3-license/)
#  Author: Fábio Pichler
#  Website: http://fabiopichler.net
#
#*******************************************************************************



if [ -e "/opt/Omicron-Player-3/uninstall" ]
then
    /opt/Omicron-Player-3/uninstall
fi
