#!/bin/bash

#*******************************************************************************
#  FPM Player Installer
#
#  Copyright (c) 2016, Fábio Pichler
#  All rights reserved.
#
#  License: BSD 3-Clause License (http://fabiopichler.net/bsd-3-license/)
#  Author: Fábio Pichler
#  Website: http://fabiopichler.net
#
#*******************************************************************************



if [ -e "/opt/FPM-Player/uninstall" ]
then
    /opt/FPM-Player/uninstall
fi
