#!/bin/bash

#*******************************************************************************
#  Omicron Player Classic Installer
#
#  Copyright (c) 2015-2019, Fábio Pichler
#  All rights reserved.
#
#  License: BSD 3-Clause License (http://fabiopichler.net/bsd-3-license/)
#  Author: Fábio Pichler
#  Website: http://fabiopichler.net
#
#*******************************************************************************



if [ -e "/opt/omicron-player-classic/uninstall" ]
then
    /opt/omicron-player-classic/uninstall
fi
