#!/bin/bash

#*******************************************************************************
#  FPM Player Installer
#
#  Copyright (c) 2016, Fábio Pichler
#  All rights reserved.
#
#  License: BSD 3-Clause License (http://fabiopichler.net/bsd-3-license/)
#  Author: Fábio Pichler
#  Website: http://fabiopichler.net
#
#*******************************************************************************

echo
echo "FPM Player (Desinstalação)"
echo "Copyright (c) 2016, Fábio Pichler, Todos os direitos Reservados"
echo

if [ ! `whoami` = "root" ]
then
    echo "Para iniciar a desinstalação, é preciso fazer login como root"
    echo
    exit
fi

count=0

echo "Iniciando o programa de desinstalação..."
echo
echo "Removendo arquivos..."

if rm "/opt/FPM-Player/" -R
then
    let count++
else
    echo "Erro ao remover os arquivos em: /opt/FPM-Player/"
fi

if rm "/usr/share/applications/FPM-Player.desktop"
then
    let count++
else
    echo "Erro ao remover o arquivo: /usr/share/applications/FPM-Player.desktop"
fi

echo

if [ $count -eq 2 ]
then
    echo "O FPM Player foi desinstalado com sucesso"
else
    echo "Erro ao desinstalar o FPM Player"
fi

echo
